liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # define your filter sets under this option
    filter_sets:
        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        thumb_medium:
            # set your image quality defaults
            jpeg_quality:          80
            png_compression_level: 7
            # setup the filter steps to apply for this transformation
            filters:
                # auto rotate the image using EXIF metadata
                auto_rotate: ~
                # strip the image of all metadata
                strip: ~
                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [530, 350]
                    mode:          outbound
                    allow_upscale: true

